"""Add weekly summaries

Revision ID: 3518811c96ff
Revises: b1507997b993
Create Date: 2026-08-02 15:32:46.920208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3518811c96ff'
down_revision = 'b1507997b993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_commencing', sa.Date(), nullable=False),
    sa.Column('route_plan', sa.Text(), nullable=False),
    sa.Column('accounts_opened', sa.Text(), nullable=False),
    sa.Column('prospects', sa.Text(), nullable=False),
    sa.Column('trade_visits', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_summaries')
    # ### end Alembic commands ###
