"""Update Sale model for executive sales analysis

Revision ID: b1507997b993
Revises: 64e2b495fccd
Create Date: 2026-07-24 16:48:03.027163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1507997b993'
down_revision = '64e2b495fccd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.drop_column('invoice_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_no', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('location')
        batch_op.drop_column('channel')

    # ### end Alembic commands ###
