"""Create trade visits table

Revision ID: ec0d06710df5
Revises: add_sales_table
Create Date: 2026-07-21 11:01:21.862393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0d06710df5'
down_revision = 'add_sales_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('sales_officer', sa.String(length=100), nullable=True),
    sa.Column('outlet_name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('outlet_type', sa.String(length=50), nullable=True),
    sa.Column('buying_razco', sa.String(length=10), nullable=True),
    sa.Column('products_purchased', sa.Text(), nullable=True),
    sa.Column('current_supplier', sa.String(length=150), nullable=True),
    sa.Column('restocking_frequency', sa.String(length=100), nullable=True),
    sa.Column('average_order_size', sa.String(length=100), nullable=True),
    sa.Column('customer_status', sa.String(length=50), nullable=True),
    sa.Column('competitor_brand', sa.String(length=100), nullable=True),
    sa.Column('competitor_product', sa.String(length=100), nullable=True),
    sa.Column('competitor_price', sa.String(length=50), nullable=True),
    sa.Column('competitor_promotion', sa.String(length=200), nullable=True),
    sa.Column('competitor_equipment', sa.String(length=200), nullable=True),
    sa.Column('display_observation', sa.Text(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=100), nullable=True),
    sa.Column('estimated_potential', sa.String(length=100), nullable=True),
    sa.Column('next_action', sa.String(length=200), nullable=True),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_visits')
    # ### end Alembic commands ###
